### ISSUE TITLE
§2.2.2 Typo: "addr" → "adder"

### ISSUE THREAD

**Issue by 0cjs** [johnwinans/rvalp#10]
§2.2.2, line 446, of Draft v0.18.1-0-g23bd3ad reads:

> This truth table shows what is called a _Full Addr._ A full addr is....

In both cases above, I believe you want "adder" (with an "e") there. Additionally, "full adder" should not have initial capitals.

**Comment by johnwinans** [comment]
Thank you.  Not sure how that stayed wrong for so long!

**Comment by johnwinans** [comment]
This was fixed in release v0.18.3
