### ISSUE TITLE
There should be no difference between imm_i and shmt_i

### ISSUE THREAD

**Issue by alexL03** [johnwinans/rvalp#2]
First i have to say that i like the figures for the immediate decoding.

I would not say, that this is an error because your decoding will also fullfill the ISA correctly.

But at an I-Type instruction the immediate should always be sign extended even if it is a shift.
This will make the implementation if the immediate decoding simpler.
(Also stated here by Andrew Waterman: https://youtu.be/XWuZSQ6lJlo?t=530)

This is because for shifting(srai,srli, slli) the ALU only needs and uses the lowest 5 bits (RV32, lowest 6/7 bits for RV64/RV128) of the immediate . (When looking in the RISC-V Reader for the srl instruction on page 165: "The least-significant five bits of x[rs2] (...) form the shift amout; the upper bits are ignored." Similar is written in the specification). So in an implementation of rv32i, for srli, x[rs2] will be replaced by the decoded immediate and the the alu will also only use the the lowest 5 bits (RV32, lowest 6/7 bits for RV64/RV128), so the upper 27 bits are ignored by the ALU, so for RV32 and the srai, srli, slli we don't need to care what is in the upper 27 bits of the decoded immediate , so we can just decode the immediate the same way as for example the addi instruction, because sign extending won't destroy the 5 relevant bits for shifting.

So please don't get me wrong, your decoding of the immediate is working and will fullfill the ISA, but i think there is an extra case which is not needed and will slow the Decoder.

I hope you understand my explanation and will take my suggested improvement into consideration.
Because the figures in the book describe the immediate decoding really good and they are a helpfully for implementing your own Risc-V on an FPGA.

**Comment by johnwinans** [comment]
Hmmm... I agree with your concern here.  But I am conflicted between documenting how the instruction behaves vs how it might be implemented.

What do you think of changing the shamt_i extraction (currently in figure 5.9) so that it is combined with 5.8 by showing the imm_i as it is and then adding a third layer (what I call a castellated box because of how the bit-positions stick out the top) showing the shamt_i result as an 'extraction' of the LSBs from the imm_i box?

The shamt_i would then only have 5 bits in an unsigned value box for the RV32I, footnote number 4 and the paragraph that refers to it would change from talking about a zero-extension to that of a 5-bit unsigned value (that is 6 or 7 respectively for the 64 and 128 bit ISAs.)

**Comment by alexL03** [comment]
I think thats a great idea because this will show the difference between the shift immediate instructions and the other arithmetic immediate instructions and how they handle the information from the immediate field. Then people will have to think about how to extend the immediate correctly so the shift immediate instructions will work correctly in their implementation or how it could be extended in a given implementation.
(Your right this book is about learning the Assembly Language of RISC-V and not how to implement your own RISC-V single-core processor and for this purpose it will make no difference. But maybe people won't use the information only for that purpose.)

I was looking through how it is done in the R-Type instructions and then i saw on page 50 to 51, for the sll instructions is written: "Shift rs1 left by the number of bits speciﬁed in the least signiﬁcant ﬁve bits of rs2 (...)" 
But for the sra and srl instruction its: "(...)-shift rs1 right by the number of bits given in rs2 (...)", where it should be also "(...)-shift rs1 right by the number of bits speciﬁed in the least signiﬁcant ﬁve bits given in rs2 (...)". Likeit is done for the sll instruction.
And maybe just for consistency (e.g. in a footnote) that there is also a difference when XLEN = 64(using the least significant 6 bits) or  XLEN = 128(using the least significant 7 bits), because for the immediate shifts it is done but not for the r-type shifts.

**Comment by johnwinans** [comment]
The rewrite did not go as I had expected... we forgot about the use of bit 30 when determining the logical/arithmetic shifting mode.  So I kept the separate shamt_i diagram... but I think it is much better.

What do you think?

**Comment by alexL03** [comment]
I think it looks good, but on the other hand Bit 30 is relevant for knowing which instruction need to be done. But it is not part of the value the operation needs.

I understand the figures which decode the immediate in that form, that they are showing the logical seperation of the instruction field in its parts.
And if the instruction field has an "constant" value for one operand of the instruction which needs to be decoded, this is done by the arrows. In my opinion Bit 30 is not part of the operand value for the shifts, it determines which shift need to be done.

But on the other hand it shows the reader that there is the exception that the immediate field contains a value/ a bit to get the operation and not only the value of an operand. I think this is the only place where this happens in the rv32i ISA.

So I agree with you and would close the issue because my last argument weights more, then the one before. It is good to show the meaning of bit 30 in the figure.

Thank you for adressing my concerns and changing the book.
