### ISSUE TITLE
Typo in the repository title: assemly

### ISSUE THREAD

**Issue by vazhnov** [johnwinans/rvalp#8]
Hello!

When I open the repository https://github.com/johnwinans/rvalp , I see "assemly" in the browser page name and also in "About" column.
I think it should be "assem**b**ly". :wink:

**Comment by johnwinans** [comment]
I guess I never read that column before!  :-D

**Comment by vazhnov** [comment]
\+ also there are tags (topics?) near "about", and there is one more typo: [assemler](https://github.com/topics/assemler).

**Comment by johnwinans** [comment]
Geez... I guess I can't type "assembly."  My repo needs better proofreading!

Thanks!
